jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run build # Ensure packages pass attw, etc.
      - run: pnpm run -r build # Build packages/site
  flint:
    name: Flint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run --filter=site prebuild # Generate packages/site/.astro
      - run: pnpm run flint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run --filter=site prebuild # Generate packages/site/.astro
      - run: pnpm run lint
  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run build # Knip requires all exports to be generated.
      - run: pnpm run lint:knip
  lint_packages:
    name: Lint Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run lint:packages
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0 # required so origin/main can be diffed
      - uses: ./.github/actions/prepare
      - name: Cache dependencies and Vite cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules/.vite
      - run: pnpm exec tsc -b # For types tests
      - run: pnpm run build -W ./packages/ts-patch/ # vitest-dev/vitest#9429
      - # Run partial test pass on PRs (only changed files)
        if: ${{ github.event_name == 'pull_request' }}
        name: Run affected tests
        run: pnpm run test --changed "origin/main"
      - # On main, run the full test suite w/ type checking
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Run full test suite
        run: pnpm run test

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
